### ISSUE TITLE
能分享一下数据集吗

### ISSUE THREAD

**Issue by ladybirdhui** [lmhgithi/2019-sohu-competition#1]
官网已经不可以下载数据集了，不知道能不能分享一下，谢谢

**Comment by lmhgithi** [comment]
https://biendata.com/competition/sohu2019/data/
我去看了下，还能下呀，是百度网盘的链接

**Comment by lmhgithi** [comment]
名称 | 格式 | 链接 | 提取码
-- | -- | -- | --
coreEntityEmotion_example.txt | txt (4.5 MB) | https://pan.baidu.com/s/1bIeSjUM8Umlrpwh0ppdLSg | 54ud
data.zip | zip (126.5 MB) | https://pan.baidu.com/s/1j5jcMlww-G7RYH2uZhLLHw | 6i6q
coreEntityEmotion_test_stage2.zip | zip (118.1 MB) | https://pan.baidu.com/s/1k9mCxTMYr9nH8bTHzrLryg | c3bg
sample_submission_stage2.txt | txt (2.4 MB) | https://pan.baidu.com/s/1h7us_vEhvq2qO5d61ozniA | 3d52
coreEntityEmotion_baseline | zip (2.1 MB) | https://github.com/sohucampus2019/coreEntityEmotion_baseline

**Comment by ladybirdhui** [comment]
谢谢了 是不能报名了，连带着不能下载数据了
你之前报名了，所以还能下载  
点赞

**Comment by MichaelMachine** [comment]
百度云没有给提取码啊

**Comment by NatLee** [comment]
您好：

**Comment by NatLee** [comment]
@lmhgithi 您好
想請問資料集下載的提取碼是什麼？
謝謝！

**Comment by TangoW** [comment]
<!DOCTYPE html>

名称 | 格式 | 链接 | MD5
-- | -- | -- | --
coreEntityEmotion_example.txt | txt 4.50MB | https://pan.baidu.com/s/1bIeSjUM8Umlrpwh0ppdLSg  ( 提取码：54ud ) ， https://www.dropbox.com/s/byhrxg4gyd8i0ak/coreEntityEmotion_example.txt?dl=0 | 4feb8bf7c35c9fb0c8ad4649b302352c
coreEntityEmotion_baseline | zip 2.12MB | https://github.com/sohucampus2019/coreEntityEmotion_baseline |  
data.zip | zip 126.50MB | https://pan.baidu.com/s/1j5jcMlww-G7RYH2uZhLLHw  ( 提取码：6i6q ) ， https://www.dropbox.com/s/afpz04h9k5c4n1l/data.zip?dl=0 | bd60736df65b22dbab4849f29f7ea72d
sample_submission_stage2.txt | txt 2.40MB | https://pan.baidu.com/s/1h7us_vEhvq2qO5d61ozniA  ( 提取码：3d52 ) ， https://www.dropbox.com/s/h4vpwpymtqq9355/coreEntityEmotion_sample_submission_stage2_v2.txt?dl=0 | 061c7c6fa846e82ac1b2683404cc1aa5
coreEntityEmotion_test_stage2.zip | zip 118.10MB | https://pan.baidu.com/s/1k9mCxTMYr9nH8bTHzrLryg  ( 提取码：c3bg ) ， https://www.dropbox.com/s/vixusvnzrd4quyt/coreEntityEmotion_test_stage2.zip?dl=0 | e8ceacc3fc40cf59789ab14f3c6326c4




最新的链接在这里：https://www.biendata.xyz/competition/sohu2019/data/
