### ISSUE TITLE
bert模型

### ISSUE THREAD

**Issue by ladybirdhui** [lmhgithi/2019-sohu-competition#2]
你好，我在调试使用bert模型时，发现它只能对字进行向量转换，而不能对词进行向量转换，觉得这样很奇怪，不知道你使用bert时也是这样，还是说我的bert设置有问题

**Comment by lmhgithi** [comment]
就是字的吧~不过我也对bert不熟悉，bert部分是队友负责的

**Comment by ladybirdhui** [comment]
好的 谢谢

**Comment by 1615070057** [comment]
bert本来就是对字的，用词可以用百度的
